site_name: Pinelang
site_url: https://paulovap.github.com/pinelang
repo_name: Pinelang
repo_url: https://github.com/paulovap/pinelang
site_description: "An small scripting language for mobile development"
site_author: Paulo Pinheiro
remote_branch: gh-pages

copyright: 'Copyright &copy; 2020 Paulo Pinheiro'

theme:
  name: 'material'
  favicon: images/pine_logo.png
  logo: images/pine_logo.png
  palette:
    primary: 'teal'
    accent: 'white'

#extra_css:
#  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - tables

nav:
  - 'API Docs':
      - 'core': latest/core/index.md
      - 'lsp': latest/lsp/index.md
      - 'android': latest/android/index.md
