// automatically generated by the FlatBuffers compiler, do not modify

package com.pinescript.ast.fbs

@Suppress("unused")
@ExperimentalUnsignedTypes
class PrimitiveType private constructor() {
    companion object {
        const val Int: UByte = 0u
        const val Double: UByte = 1u
        const val String: UByte = 2u
        const val Boolean: UByte = 3u
        const val ObjectProperty: UByte = 4u
        val names : Array<String> = arrayOf("Int", "Double", "String", "Boolean", "ObjectProperty")
        fun name(e: Int) : String = names[e]
    }
}
