// automatically generated by the FlatBuffers compiler, do not modify

package com.pinescript.fbs.ast

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class BinaryExpr : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : BinaryExpr {
        __init(_i, _bb)
        return this
    }
    val op : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val callIdx : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_1_12_0()
        fun getRootAsBinaryExpr(_bb: ByteBuffer): BinaryExpr = getRootAsBinaryExpr(_bb, BinaryExpr())
        fun getRootAsBinaryExpr(_bb: ByteBuffer, obj: BinaryExpr): BinaryExpr {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createBinaryExpr(builder: FlatBufferBuilder, op: Long, callIdx: Byte) : Int {
            builder.startTable(2)
            addOp(builder, op)
            addCallIdx(builder, callIdx)
            return endBinaryExpr(builder)
        }
        fun startBinaryExpr(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addOp(builder: FlatBufferBuilder, op: Long) = builder.addLong(0, op, 0L)
        fun addCallIdx(builder: FlatBufferBuilder, callIdx: Byte) = builder.addByte(1, callIdx, 0)
        fun endBinaryExpr(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
