// automatically generated by the FlatBuffers compiler, do not modify

package com.pinescript.fbs.ast

@Suppress("unused")
@ExperimentalUnsignedTypes
class BinaryOp private constructor() {
    companion object {
        const val PLUS: Byte = 0
        const val MINUS: Byte = 1
        const val MULTI: Byte = 2
        const val DIV: Byte = 3
        const val REMAINDER: Byte = 4
        const val AND: Byte = 5
        const val OR: Byte = 6
        val names : Array<String> = arrayOf("PLUS", "MINUS", "MULTI", "DIV", "REMAINDER", "AND", "OR")
        fun name(e: Int) : String = names[e]
    }
}
