// automatically generated by the FlatBuffers compiler, do not modify

package com.pinescript.fbs.ast

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class BoolProp : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : BoolProp {
        __init(_i, _bb)
        return this
    }
    val id : Byte get() = bb.get(bb_pos + 0)
    val value : Byte get() = bb.get(bb_pos + 1)
    companion object {
        fun createBoolProp(builder: FlatBufferBuilder, id: Byte, value: Byte) : Int {
            builder.prep(1, 2)
            builder.putByte(value)
            builder.putByte(id)
            return builder.offset()
        }
    }
}
