// automatically generated by the FlatBuffers compiler, do not modify

package com.pinescript.fbs.ast

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class CallableExpression : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CallableExpression {
        __init(_i, _bb)
        return this
    }
    val objId : Long get() = bb.getLong(bb_pos + 0)
    val callIdx : Byte get() = bb.get(bb_pos + 8)
    companion object {
        fun createCallableExpression(builder: FlatBufferBuilder, objId: Long, callIdx: Byte) : Int {
            builder.prep(8, 16)
            builder.pad(7)
            builder.putByte(callIdx)
            builder.putLong(objId)
            return builder.offset()
        }
    }
}
