// automatically generated by the FlatBuffers compiler, do not modify

package com.pinescript.fbs.ast

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class DoubleProp : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DoubleProp {
        __init(_i, _bb)
        return this
    }
    val id : Byte get() = bb.get(bb_pos + 0)
    val value : Double get() = bb.getDouble(bb_pos + 8)
    companion object {
        fun createDoubleProp(builder: FlatBufferBuilder, id: Byte, value: Double) : Int {
            builder.prep(8, 16)
            builder.putDouble(value)
            builder.pad(7)
            builder.putByte(id)
            return builder.offset()
        }
    }
}
