// automatically generated by the FlatBuffers compiler, do not modify

package com.pinescript.fbs.ast

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class IntProp : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : IntProp {
        __init(_i, _bb)
        return this
    }
    val id : Byte get() = bb.get(bb_pos + 0)
    val value : Int get() = bb.getInt(bb_pos + 4)
    companion object {
        fun createIntProp(builder: FlatBufferBuilder, id: Byte, value: Int) : Int {
            builder.prep(4, 8)
            builder.putInt(value)
            builder.pad(3)
            builder.putByte(id)
            return builder.offset()
        }
    }
}
