// automatically generated by the FlatBuffers compiler, do not modify

package com.pinescript.fbs.ast

@Suppress("unused")
@ExperimentalUnsignedTypes
class PropType private constructor() {
    companion object {
        const val Int: Byte = 0
        const val Double: Byte = 1
        const val String: Byte = 2
        const val Boolean: Byte = 3
        const val ObjectProperty: Byte = 4
        const val Expression: Byte = 5
        val names : Array<String> = arrayOf("Int", "Double", "String", "Boolean", "ObjectProperty", "Expression")
        fun name(e: Int) : String = names[e]
    }
}
